lesson 37
DmitriiYaganin/diplomady pull request #5
Opened 2023-03-25 09:49 UTC by DmitriiYaganin

2023-03-26 09:21 UTC, painassasin requested changes

2023-03-26 09:21 UTC, painassasin commented on todolist/goals/admin.py
> +from todolist.goals.models import GoalCategory, Goal, GoalComment
Не хватает классов в админке для управления досками и участниками досок

2023-03-26 09:21 UTC, painassasin commented on todolist/goals/serializers.py
>  class GoalCategoryCreateSerializer(serializers.ModelSerializer):
Категорию можно создать только на Не удаленных досках и нужны права owner или writer - это нужно учесть в валидаторе доски
То же самое касается Сериализаторов на Цели и Комментарии

2023-03-26 09:57 UTC, DmitriiYaganin commented on todolist/goals/admin.py
> +from todolist.goals.models import GoalCategory, Goal, GoalComment
Да, забыл добавил.

2023-03-26 10:00 UTC, DmitriiYaganin commented on todolist/goals/serializers.py
>  class GoalCategoryCreateSerializer(serializers.ModelSerializer):
А здесь же в permissions.py проверяем на владельцев и  далее во views.py в permission_classes = прописываем наши пермишены.

2023-03-26 10:24 UTC, painassasin commented on todolist/goals/serializers.py
>  class GoalCategoryCreateSerializer(serializers.ModelSerializer):
В `permissions` мы проверяем через метод `has_obj_permission` - нужен объект. Он есть только в классах, котоыре используют функцию `get_object` в своих миксинах - `Retrieve`, `Update`, `Destory`. Класс `Create` не использует этот метод, поэтому для него функциональность нужно прописать в валидаторе

2023-03-26 11:35 UTC, DmitriiYaganin commented on todolist/goals/serializers.py
>  class GoalCategoryCreateSerializer(serializers.ModelSerializer):
А, не так понял изначально, пропишу валидаторы

2023-03-26 11:36 UTC, DmitriiYaganin commented on todolist/goals/serializers.py
>  class GoalCategoryCreateSerializer(serializers.ModelSerializer):
Как отправить код?
serializer.py:
from datetime import date

from django.db import transaction
from django.utils import timezone
from rest_framework import serializers
from rest_framework.exceptions import PermissionDenied, ValidationError

from todolist.core.models import User
from todolist.core.serializers import ProfileSerializer
from todolist.goals.models import GoalCategory, Goal, GoalComment, Board, BoardParticipant


class GoalCategoryCreateSerializer(serializers.ModelSerializer):
    user = serializers.HiddenField(default=serializers.CurrentUserDefault())

    class Meta:
        model = GoalCategory
        read_only_fields = ('id', 'created', 'updated', 'user', 'is_deleted')
        fields = '__all__'


class GoalCategorySerializer(serializers.ModelSerializer):
    user = ProfileSerializer(read_only=True)

    class Meta:
        model = GoalCategory
        fields = '__all__'
        read_only_fields = ('id', 'created', 'updated', 'user')


class GoalCreateSerializer(serializers.ModelSerializer):
    user = serializers.HiddenField(default=serializers.CurrentUserDefault())

    class Meta:
        model = Goal
        fields = '__all__'
        read_only_fields = ('id', 'created', 'updated', 'user')

    def validate_category(self, value: GoalCategory) -> GoalCategory:
        if value.is_deleted:
            raise ValidationError('Goal not found')
        if self.context['request'].user.id != value.user_id:
            raise PermissionDenied
        return value

    def validate_due_date(self, value: date) -> date:
        if value and value < timezone.now().date():
            raise ValidationError('Failed set due date in past')
        return value


class GoalSerializer(serializers.ModelSerializer):
    user = ProfileSerializer(read_only=True)

    class Meta:
        model = Goal
        fields = '__all__'
        read_only_fields = ('id', 'created', 'updated', 'user')

    def validate_category(self, value: GoalCategory) -> GoalCategory:
        if value.is_deleted:
            raise ValidationError('Goal not found')
        if self.context['request'].user.id != value.user_id:
            raise PermissionDenied
        return value


class GoalCommentCreateSerializer(serializers.ModelSerializer):
    user = serializers.HiddenField(default=serializers.CurrentUserDefault())

    def validate_goal(self, value: Goal) -> Goal:
        if value.status == Goal.Status.archived:
            raise ValidationError('Goal not found')
        if self.context['request'].user.id != value.user_id:
            raise PermissionDenied
        return value

    class Meta:
        model = GoalComment
        fields = '__all__'
        read_only_fields = ('id', 'created', 'update', 'user')


class GoalCommentSerializer(serializers.ModelSerializer):
    user = ProfileSerializer(read_only=True)

    def validate_goal(self, value: Goal) -> Goal:
        if value.status == Goal.Status.archived:
            raise ValidationError('Goal not found')
        if self.context['request'].user.id != value.user_id:
            raise PermissionDenied
        return value

    class Meta:
        model = GoalComment
        fields = '__all__'
        read_only_fields = ('id', 'created', 'update', 'user', 'goal')


class BoardCreateSerializer(serializers.ModelSerializer):

    class Meta:
        model = Board
        read_only_fields = ('id', 'created', 'updated', 'is_deleted')
        fields = '__all__'


class BoardParticipantSerializer(serializers.ModelSerializer):
    role = serializers.ChoiceField(required=True, choices=BoardParticipant.Role.choices[1:])
    user = serializers.SlugRelatedField(slug_field='username', queryset=User.objects.all())

    class Meta:
        model = BoardParticipant
        fields = '__all__'
        read_only_fields = ('id', 'created', 'updated', 'board')


class BoardSerializer(serializers.ModelSerializer):
    participants = BoardParticipantSerializer(many=True)

    class Meta:
        model = Board
        fields = '__all__'
        read_only_fields = ('id', 'created', 'updated', 'is_deleted')

    def update(self, instance: Board, validated_data: dict) -> Board:
        with transaction.atomic():
            BoardParticipant.objects.filter(board=instance).exclude(user=self.context['request'].user).delete()
            BoardParticipant.objects.bulk_create([
                BoardParticipant(
                    user=participant['user'],
                    role=participant['role'],
                    board=instance
                )
                for participant in validated_data.get('participants', [])
            ])

            if title := validated_data.get('title'):
                instance.title = title
                instance.save(update_fields=('title',))

        return instance

    def validate_category(self, value: GoalCategory) -> GoalCategory:
        if value.is_deleted:
            raise ValidationError('Goal not found')
        if self.context['request'].user.id != value.user_id:
            raise PermissionDenied
        return value

2023-03-26 11:48 UTC, DmitriiYaganin commented on todolist/goals/serializers.py
>  class GoalCategoryCreateSerializer(serializers.ModelSerializer):
Biard переименовал:   
 def validate_board(self, value: Board) -> Board:
        if value.is_deleted:
            raise ValidationError('Goal not found')
        if self.context['request'].user.id != value:
            raise PermissionDenied
        return value

2023-03-26 11:49 UTC, DmitriiYaganin commented on todolist/goals/serializers.py
>  class GoalCategoryCreateSerializer(serializers.ModelSerializer):
Board переименовал:
    def validate_board(self, value: Board) -> Board:
        if value.is_deleted:
            raise ValidationError('Goal not found')
        if self.context['request'].user.id != value:
            raise PermissionDenied
        return value

2023-03-26 20:47 UTC, painassasin requested changes

2023-03-26 20:47 UTC, painassasin commented on todolist/goals/serializers.py
> +    def validate_board(self, value: Board) -> Board:
Этот валидатор не нужен - он ничего не валидирует (поля board у доски нет)

2023-03-26 20:47 UTC, painassasin commented on todolist/goals/serializers.py
> +    def validate_goal(self, value: GoalCategory) -> GoalCategory:
ТУт нужно валидировать категорию (у цели нет цели - у нее есть категория)

2023-03-27 07:11 UTC, DmitriiYaganin commented on todolist/goals/serializers.py
> +    def validate_board(self, value: Board) -> Board:
Ага, убрал.

2023-03-27 07:19 UTC, DmitriiYaganin commented on todolist/goals/serializers.py
> +    def validate_goal(self, value: GoalCategory) -> GoalCategory:
Ага, при чем изначально было верно, чет за сомневался. Поправил, повторно выгрузил.

2023-03-27 12:51 UTC, painassasin approved these changes

2023-03-27 16:57 UTC, merged